#Sample .travis.yml for R projects

language: r
r:
 - 3.3.3
 - release
 - devel
package: cache
r_build_args: " --no-resave-data"
r_check_args: "--timings"
-os:
  - linux
  - osx
  - windows
branches:
  except:
  - legacy